# -*- coding: utf-8 -*-
"""TR -> EN, 2. tur: yorum DUZYAZISI. Uzun ifade ONCE."""
SOZLUK2 = {
 # --- baslik kaliplari (bu depoda cok tekrar eder) ---
 "NEDEN VAR": "WHY IT EXISTS", "NEDEN AYRI": "WHY SEPARATE",
 "NEDEN SART": "WHY REQUIRED", "NEDEN OGRENME": "WHY LEARNED",
 "NEDEN": "WHY", "OLCULDU": "MEASURED", "OLCULMEDI": "NOT MEASURED",
 "DIKKAT": "NOTE", "UYARI": "WARNING", "ONEMLI": "IMPORTANT",
 "SONUC": "RESULT", "HUKUM": "VERDICT", "KARAR": "DECISION",
 "GEREKCE": "RATIONALE", "MAKBUZ": "RECEIPT", "MAKBUZLAR": "RECEIPTS",
 "DERS": "LESSON", "KOK NEDEN": "ROOT CAUSE", "KUSUR": "DEFECT",
 "TUZAK": "TRAP", "KURAL": "RULE", "AMAC": "PURPOSE", "HEDEF": "TARGET",
 "SEBEP": "REASON", "ORNEK": "EXAMPLE", "OZET": "SUMMARY",
 "GUVENLIK": "SAFETY", "DOGRULAMA": "VERIFICATION", "KONTROL": "CHECK",
 "BULGU": "FINDING", "TESHIS": "DIAGNOSIS", "ONARIM": "FIX",
 "DAGITILDI": "DEPLOYED", "DAGITILMADI": "NOT DEPLOYED",
 "KAPANDI": "CLOSED", "ACIK": "OPEN", "IPTAL": "CANCELLED",
 "GERI ALINDI": "REVERTED", "GECERSIZ": "INVALID", "GECERLI": "VALID",
 # --- baglaclar / edatlar ---
 "cunku": "because", "yani": "i.e.", "ancak": "however", "ama": "but",
 "ayrica": "also", "boylece": "so", "dolayisiyla": "therefore",
 "bu yuzden": "that is why", "buna karsilik": "in contrast",
 "ornegin": "for example", "yoksa": "otherwise", "eger": "if",
 "ise": "whereas", "ve": "and", "veya": "or", "ile": "with",
 "icin": "for", "gore": "according to", "kadar": "up to",
 "uzere": "so as to", "ragmen": "despite", "yerine": "instead of",
 "once": "before", "sonra": "after", "sirasinda": "during",
 "asagida": "below", "yukarida": "above", "burada": "here",
 "bkz": "see", "Bkz": "See",
 # --- fiiller ---
 "kullanilir": "is used", "kullaniliyor": "is used",
 "hesaplanir": "is computed", "hesaplaniyor": "is computed",
 "doner": "returns", "dondurur": "returns", "alir": "takes",
 "verir": "gives", "yazar": "writes", "okur": "reads",
 "yapilir": "is done", "yapiyor": "does", "calisir": "works",
 "calismiyor": "does not work", "gerekir": "is required",
 "gerekiyor": "is required", "olmali": "must be",
 "olabilir": "may be", "degistirir": "changes", "degismez": "does not change",
 "bozar": "breaks", "duzeltir": "fixes", "atlar": "skips",
 "secer": "selects", "bulur": "finds", "uretir": "produces",
 "tasir": "carries", "tutar": "keeps", "siler": "deletes",
 "ekler": "adds", "cikarir": "removes", "kirpar": "clips",
 "birlestirir": "merges", "ayirir": "separates", "kosar": "runs",
 "kosuldu": "was run", "denendi": "was tried", "bulundu": "was found",
 "gosterdi": "showed", "soyluyor": "says", "anlamina gelir": "means",
 # --- nitelemeler ---
 "her zaman": "always", "asla": "never", "bazen": "sometimes",
 "genelde": "usually", "yalniz": "only", "yalnizca": "only",
 "sadece": "only", "zaten": "already", "hala": "still",
 "artik": "now", "henuz": "yet", "hicbir": "no", "hepsi": "all",
 "bazi": "some", "cogu": "most", "en az": "at least",
 "en cok": "at most", "yaklasik": "approximately", "yaklasik olarak": "roughly",
 "esit": "equal", "farkli": "different", "ayni": "same",
 "dogru": "correct", "yanlis": "wrong", "eksik": "missing",
 "fazla": "extra", "bos": "empty", "dolu": "full",
 "acik": "open", "kapali": "closed", "gercek": "real",
 "sahte": "fake", "eski": "old", "yeni": "new",
 "buyuk": "large", "kucuk": "small", "yuksek": "high", "dusuk": "low",
 "hizli": "fast", "yavas": "slow", "kolay": "easy", "zor": "hard",
 "guvenli": "safe", "riskli": "risky", "sessiz": "silent",
 "gizli": "hidden", "belirsiz": "ambiguous", "kesin": "conclusive",
 # --- alan sozcukleri (1. turde olmayanlar) ---
 "nokta": "point", "noktalar": "points", "cizgi": "line",
 "yuzey": "surface", "tepe": "vertex", "tepeler": "vertices",
 "yuz": "face", "kenar": "edge", "mesh": "mesh", "olcek": "scale",
 "boyut": "size", "genislik": "width", "yukseklik": "height",
 "mesafe": "distance", "aci": "angle", "yaricap": "radius",
 "merkez": "centre", "sinir": "boundary", "bolge": "region",
 "kanal": "channel", "delik": "hole", "duvar": "wall",
 "model": "model", "modeller": "models", "ag": "network",
 "katman": "layer", "bas": "head", "girdi": "input", "cikti": "output",
 "veri": "data", "etiket": "label", "etiketler": "labels",
 "ozellik": "feature", "oznitelik": "feature", "oznitelikler": "features",
 "sutun": "column", "satir": "row", "dizi": "array", "liste": "list",
 "sozluk": "dictionary", "dosya": "file", "dizin": "directory",
 "yol": "path", "ad": "name", "adlar": "names", "surec": "process",
 "adim": "step", "asama": "stage", "dongu": "loop", "kosul": "condition",
 "durum": "state", "sonuclar": "results", "sayilar": "numbers",
 "toplam": "total", "ortalama": "mean", "ortanca": "median",
 "yayilim": "spread", "dagilim": "distribution", "orneklem": "sample",
 "agirlik": "weight", "agirliklar": "weights", "puan": "score",
 "siralama": "ranking", "sira": "order", "adet": "count",
 "birim": "unit", "carpim": "product", "fark": "difference",
 "artik": "residual", "kayma": "offset", "duzeltme": "correction",
 "tahmin": "prediction", "gercek deger": "ground truth",
}

SOZLUK2.update({
 "bir": "a", "bu": "this", "su": "this", "o": "that", "her": "each",
 "hepsi": "all of them", "hicbiri": "none of them", "hic": "never",
 "cok": "very", "daha": "more", "en": "most", "az": "few",
 "yok": "absent", "var": "present", "degil": "not", "olarak": "as",
 "olan": "which is", "olur": "becomes", "oldu": "became",
 "kural": "rule", "kaynak": "source", "deger": "value", "sayi": "number",
 "sayisi": "count", "kere": "times", "defa": "times", "kez": "times",
 "tur": "kind", "tip": "type", "sekil": "shape", "bicim": "form",
 "gibi": "like", "kendi": "own", "birbirine": "each other",
 "arasinda": "between", "icinde": "inside", "disinda": "outside",
 "uzerinde": "on", "altinda": "under", "yaninda": "next to",
 "boyunca": "along", "sirasi": "order", "yerde": "places",
 "tarafindan": "by", "sayesinde": "thanks to", "ragmen": "despite",
 "iki": "two", "uc": "three", "dort": "four", "bes": "five",
 "alti": "six", "yedi": "seven", "sekiz": "eight", "dokuz": "nine",
 "on": "ten", "ilk": "first", "son": "last", "orta": "middle",
 "ust": "upper", "alt": "lower", "sol": "left", "sag": "right",
 "tek": "single", "cift": "double", "yarim": "half", "tam": "full",
})
